import {Inter} from 'next/font/google'
import Head from 'next/head'
import Link from 'next/link'

const inter = Inter({subsets: ['latin']})

export default function Home() {
  return (
    <>
      <Head>
        <title>Page 2</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <h1>Page 2</h1>
      <p>
        <span>
          Go to <Link href='/'> Home </Link>
        </span>
      </p>
    </>
  )
}
